services:
  webserver:
    image: nginx
    container_name: webserver
    volumes:
      - ./webserver/nginx.conf:/etc/nginx/nginx.conf
      - ./webserver/includes/:/etc/nginx/includes/
      - ./webserver/html:/usr/share/nginx/html/
      - ./webserver/html/usager/images:/var/www/html/static/images
    ports:
      - "80:80"
    networks:
      - acad-net

  auth:
    image: quay.io/keycloak/keycloak:19.0.3
    container_name: auth
    volumes:
      - ./keycloak/data:/var/tmp
      - ./keycloak/startup-scripts/init.sh:/opt/jboss/tools/docker-entrypoint.sh
    entrypoint: sh -c "/opt/jboss/tools/docker-entrypoint.sh"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_PROXY: edge
      DB_VENDOR: postgres
      DB_ADDR: database
      DB_DATABASE: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
    ports:
      - "8180:8180"
    depends_on:
      - database
    networks:
      - acad-net

  database:
    image: postgres:13
    container_name: database
    restart: always
    ports:
      - "5444:5432"
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    networks:
      - acad-net

networks:
  acad-net: